//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intento2ado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_c
    {
        public int id { get; set; }
        public string produc { get; set; }
        public Nullable<int> canti { get; set; }
        public Nullable<int> compra { get; set; }
    
        public virtual compra compra1 { get; set; }
        public virtual prod prod { get; set; }
    }
}
