//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intento2ado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_v
    {
        public int id { get; set; }
        public string produc { get; set; }
        public Nullable<int> canti { get; set; }
        public Nullable<int> venta { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual prod prod { get; set; }
        public virtual venta venta1 { get; set; }
    }
}
