//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intento2ado.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MINIMARKETEntities : DbContext
    {
        public MINIMARKETEntities()
            : base("name=MINIMARKETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categ> categ { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<detalle_c> detalle_c { get; set; }
        public virtual DbSet<detalle_v> detalle_v { get; set; }
        public virtual DbSet<prod> prod { get; set; }
        public virtual DbSet<prov> prov { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vend> vend { get; set; }
        public virtual DbSet<venta> venta { get; set; }
    }
}
