//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intento2ado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prod()
        {
            this.detalle_c = new HashSet<detalle_c>();
            this.detalle_v = new HashSet<detalle_v>();
        }
    
        public string id { get; set; }
        public string nom { get; set; }
        public string detalle { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> cat { get; set; }
        public Nullable<int> canti { get; set; }
    
        public virtual categ categ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_c> detalle_c { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_v> detalle_v { get; set; }
    }
}
